spring:
  datasource:
    url: ${H2_URL}
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        id:
          new_generator_mappings: true

  flyway:
    locations: classpath:db/migration/h2
    baselineOnMigrate: true
    enabled: false