autoCommit=false
minimumIdle=5
maximumPoolSize=20
idleTimeout=30000
poolName=SpringBootJPAHikariCP
maxLifetime=2000000
connectionTimeout=30000
connectionTestQuery=select * from pyram_user
driverClassName=org.postgresql.Driver