CREATE TABLE PYRAM_ROLE (
   ID  BIGSERIAL NOT NULL,
   NAME VARCHAR(255),
   PRIMARY KEY (ID)
);

ALTER TABLE IF EXISTS PYRAM_ROLE ADD CONSTRAINT AUTHORITY_NAME UNIQUE (NAME);

CREATE TABLE PYRAM_USER (
       ID  BIGSERIAL NOT NULL,
       ACCOUNT_EXPIRED BOOLEAN,
       ACCOUNT_LOCKED BOOLEAN,
       CREDENTIALS_EXPIRED BOOLEAN,
       ENABLED BOOLEAN,
       PASSWORD VARCHAR(255),
       USER_NAME VARCHAR(255),
       CREATED_AT TIMESTAMP(6) WITHOUT TIME zone,
       PRIMARY KEY (ID)
);

ALTER TABLE IF EXISTS PYRAM_USER ADD CONSTRAINT USER_USER_NAME UNIQUE (USER_NAME);

CREATE TABLE USERS_AUTHORITIES (
   USER_ID INT8 NOT NULL,
   AUTHORITY_ID INT8 NOT NULL,
   PRIMARY KEY (USER_ID, AUTHORITY_ID)
);

ALTER TABLE IF EXISTS USERS_AUTHORITIES ADD CONSTRAINT USERS_AUTHORITIES_AUTHORITY
    FOREIGN KEY (AUTHORITY_ID) REFERENCES PYRAM_ROLE;

ALTER TABLE IF EXISTS USERS_AUTHORITIES ADD CONSTRAINT USERS_AUTHORITIES_USER_
    FOREIGN KEY (USER_ID) REFERENCES PYRAM_USER;