INSERT INTO PYRAM_ROLE(ID, NAME) VALUES (1, 'ADMIN_CREATE');
INSERT INTO PYRAM_ROLE(ID, NAME) VALUES (2, 'ADMIN_READ');
INSERT INTO PYRAM_ROLE(ID, NAME) VALUES (3, 'ADMIN_UPDATE');
INSERT INTO PYRAM_ROLE(ID, NAME) VALUES (4, 'ADMIN_DELETE');

INSERT INTO PYRAM_ROLE(ID, NAME) VALUES (5, 'MANAGE_CREATE');
INSERT INTO PYRAM_ROLE(ID, NAME) VALUES (6, 'MANAGE_READ');
INSERT INTO PYRAM_ROLE(ID, NAME) VALUES (7, 'MANAGE_UPDATE');
INSERT INTO PYRAM_ROLE(ID, NAME) VALUES (8, 'MANAGE_DELETE');

INSERT INTO PYRAM_ROLE(ID, NAME) VALUES (9, 'ROLE_PYRAMID_READER');