INSERT INTO PYRAM_USER (ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED, CREATED_AT)
VALUES (1, 'admin', '$2a$10$DepPk9PGez7L8tuIqhqgDOrctJ6qU3QjV4GSBWT4DhF5gNgtLAsNa', FALSE, FALSE, FALSE, TRUE, NOW());

INSERT INTO PYRAM_USER(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED, CREATED_AT)
VALUES (2, 'reader', '$2a$10$jV1XHZoTtGbh0Ggu8SCGR.zcRbl6gpQ47vQyXBRuhEL6OHkWMNhm2', FALSE, FALSE, FALSE, TRUE, NOW());

INSERT INTO PYRAM_USER(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED, CREATED_AT)
VALUES (3, 'modifier', '$2a$10$jCwX2rtH6ccMiKdJuID4geJPTISmC61qCsKb.ZorKZsiLGEhU4ZUu', FALSE, FALSE, FALSE, TRUE, NOW());

INSERT INTO PYRAM_USER(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED, CREATED_AT)
VALUES (4, 'reader2', '$2a$10$Et3E61UsqgfFv9Foufxryu5uyzjZQbiza5BYu3PoG9..e1nP.AcXG', FALSE, FALSE, FALSE, TRUE, NOW());

INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (1, 2);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (1, 3);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (1, 4);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (1, 5);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (1, 6);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (1, 7);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (1, 8);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (1, 9);

INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (2, 2);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (2, 6);

INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (3, 3);
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (3, 7);

INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (4, 9);
